version: "3.8"

services:
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: ai_service
    ports:
      - "8000:8000"
    volumes:
      - ./shared/uploads:/app/../shared/uploads
    environment:
      - PYTHONUNBUFFERED=1

  ui_service:
    build:
      context: ./ui_service
      dockerfile: Dockerfile
    container_name: ui_service
    ports:
      - "5050:5050"
    volumes:
      - ./shared/uploads:/app/../shared/uploads
    depends_on:
      - ai_service
    environment:
      - PYTHONUNBUFFERED=1
      - AI_SERVICE_URL=http://ai_service:8000/detect
